/*
 * Internal API of remote card management service
 * Internal API of remote card management service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coinclave.crypto.applet.update.network.client;

import com.google.gson.reflect.TypeToken;
import io.coinclave.crypto.applet.update.network.invoker.ApiCallback;
import io.coinclave.crypto.applet.update.network.invoker.ApiClient;
import io.coinclave.crypto.applet.update.network.invoker.ApiException;
import io.coinclave.crypto.applet.update.network.invoker.ApiResponse;
import io.coinclave.crypto.applet.update.network.invoker.Configuration;
import io.coinclave.crypto.applet.update.network.invoker.Pair;
import io.coinclave.crypto.applet.update.network.models.APDUCommand;
import io.coinclave.crypto.applet.update.network.models.UpdateCardProgressRequest;
import io.coinclave.crypto.applet.update.network.models.UpdateCardRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CardApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CardApi() {
        this(Configuration.getDefaultApiClient());
    }

    public CardApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for patchUpdateCard
     * @param updateCardProgressRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success patch update card session </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchUpdateCardCall(UpdateCardProgressRequest updateCardProgressRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateCardProgressRequest;

        // create path and map variables
        String localVarPath = "/remote-card-management/cards";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call patchUpdateCardValidateBeforeCall(UpdateCardProgressRequest updateCardProgressRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = patchUpdateCardCall(updateCardProgressRequest, _callback);
        return localVarCall;

    }

    /**
     * Command for update card applet process progress
     * 
     * @param updateCardProgressRequest  (optional)
     * @return List&lt;APDUCommand&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success patch update card session </td><td>  -  </td></tr>
     </table>
     */
    public List<APDUCommand> patchUpdateCard(UpdateCardProgressRequest updateCardProgressRequest) throws ApiException {
        ApiResponse<List<APDUCommand>> localVarResp = patchUpdateCardWithHttpInfo(updateCardProgressRequest);
        return localVarResp.getData();
    }

    /**
     * Command for update card applet process progress
     * 
     * @param updateCardProgressRequest  (optional)
     * @return ApiResponse&lt;List&lt;APDUCommand&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success patch update card session </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<APDUCommand>> patchUpdateCardWithHttpInfo(UpdateCardProgressRequest updateCardProgressRequest) throws ApiException {
        okhttp3.Call localVarCall = patchUpdateCardValidateBeforeCall(updateCardProgressRequest, null);
        Type localVarReturnType = new TypeToken<List<APDUCommand>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Command for update card applet process progress (asynchronously)
     * 
     * @param updateCardProgressRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success patch update card session </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchUpdateCardAsync(UpdateCardProgressRequest updateCardProgressRequest, final ApiCallback<List<APDUCommand>> _callback) throws ApiException {

        okhttp3.Call localVarCall = patchUpdateCardValidateBeforeCall(updateCardProgressRequest, _callback);
        Type localVarReturnType = new TypeToken<List<APDUCommand>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateCard
     * @param updateCardRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success start update card session </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateCardCall(UpdateCardRequest updateCardRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateCardRequest;

        // create path and map variables
        String localVarPath = "/remote-card-management/cards";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateCardValidateBeforeCall(UpdateCardRequest updateCardRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = updateCardCall(updateCardRequest, _callback);
        return localVarCall;

    }

    /**
     * Command for update card applet
     * 
     * @param updateCardRequest  (optional)
     * @return List&lt;APDUCommand&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success start update card session </td><td>  -  </td></tr>
     </table>
     */
    public List<APDUCommand> updateCard(UpdateCardRequest updateCardRequest) throws ApiException {
        ApiResponse<List<APDUCommand>> localVarResp = updateCardWithHttpInfo(updateCardRequest);
        return localVarResp.getData();
    }

    /**
     * Command for update card applet
     * 
     * @param updateCardRequest  (optional)
     * @return ApiResponse&lt;List&lt;APDUCommand&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success start update card session </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<APDUCommand>> updateCardWithHttpInfo(UpdateCardRequest updateCardRequest) throws ApiException {
        okhttp3.Call localVarCall = updateCardValidateBeforeCall(updateCardRequest, null);
        Type localVarReturnType = new TypeToken<List<APDUCommand>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Command for update card applet (asynchronously)
     * 
     * @param updateCardRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success start update card session </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateCardAsync(UpdateCardRequest updateCardRequest, final ApiCallback<List<APDUCommand>> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateCardValidateBeforeCall(updateCardRequest, _callback);
        Type localVarReturnType = new TypeToken<List<APDUCommand>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
