/*
 * Internal API of remote card management service
 * Internal API of remote card management service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coinclave.crypto.applet.update.network.models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * APDUCommandResponse
 */
public class APDUCommandResponse {
  public static final String SERIALIZED_NAME_COMMAND = "command";
  @SerializedName(SERIALIZED_NAME_COMMAND)
  private String command;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_RESPONSE = "response";
  @SerializedName(SERIALIZED_NAME_RESPONSE)
  private String response;

  public APDUCommandResponse() { 
  }

  public APDUCommandResponse command(String command) {
    
    this.command = command;
    return this;
  }

   /**
   * APDU command
   * @return command
  **/

  public String getCommand() {
    return command;
  }


  public void setCommand(String command) {
    this.command = command;
  }


  public APDUCommandResponse description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description of APDU command
   * @return description
  **/

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public APDUCommandResponse response(String response) {
    
    this.response = response;
    return this;
  }

   /**
   * Response of execute APDU command
   * @return response
  **/

  public String getResponse() {
    return response;
  }


  public void setResponse(String response) {
    this.response = response;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APDUCommandResponse apDUCommandResponse = (APDUCommandResponse) o;
    return Objects.equals(this.command, apDUCommandResponse.command) &&
        Objects.equals(this.description, apDUCommandResponse.description) &&
        Objects.equals(this.response, apDUCommandResponse.response);
  }

  @Override
  public int hashCode() {
    return Objects.hash(command, description, response);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APDUCommandResponse {\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

