/*
 * Internal API of remote card management service
 * Internal API of remote card management service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coinclave.crypto.applet.update.network.models;

import com.google.gson.annotations.SerializedName;

import java.util.List;
import java.util.Objects;

/**
 * CheckAppletVersionResponse
 */
public class CheckAppletVersionResponse {
  @SerializedName("sessionId")
  private String sessionId;

  @SerializedName("apduCommands")
  private List<APDUCommand> apduCommands = null;

  @SerializedName("result")
  private CheckAppletVersionData result;

  public CheckAppletVersionResponse() { 
  }

  public CheckAppletVersionResponse sessionId(String sessionId) {

    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get version
   * @return version
  **/

  public String getSessionId() {
    return sessionId;
  }


  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public CheckAppletVersionResponse apduCommands(List<APDUCommand> apduCommands) {
    
    this.apduCommands = apduCommands;
    return this;
  }

   /**
   * Get needUpdate
   * @return needUpdate
  **/

  public List<APDUCommand> getApduCommands() {
    return apduCommands;
  }


  public void setApduCommands(List<APDUCommand> apduCommands) {
    this.apduCommands = apduCommands;
  }


  public CheckAppletVersionResponse result(CheckAppletVersionData result) {
    
    this.result = result;
    return this;
  }

   /**
   * Get critical
   * @return critical
  **/

  public CheckAppletVersionData getResult() {
    return result;
  }


  public void setResult(CheckAppletVersionData result) {
    this.result = result;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckAppletVersionResponse checkAppletVersionResponse = (CheckAppletVersionResponse) o;
    return Objects.equals(this.sessionId, checkAppletVersionResponse.sessionId) &&
        Objects.equals(this.apduCommands, checkAppletVersionResponse.apduCommands) &&
        Objects.equals(this.result, checkAppletVersionResponse.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionId, apduCommands, result);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckAppletVersionResponse {\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    apduCommands: ").append(toIndentedString(apduCommands)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

