/*
 * Internal API of remote card management service
 * Internal API of remote card management service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.coinclave.crypto.applet.update.network.models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * UpdateCardRequest
 */
public class UpdateCardRequest {
  public static final String SERIALIZED_NAME_CARD_ID = "cardId";
  @SerializedName(SERIALIZED_NAME_CARD_ID)
  private String cardId;

  public static final String SERIALIZED_NAME_CURRENT_APPLET_VERSION = "currentAppletVersion";
  @SerializedName(SERIALIZED_NAME_CURRENT_APPLET_VERSION)
  private String currentAppletVersion;

  public static final String SERIALIZED_NAME_NEW_APPLET_VERSION = "newAppletVersion";
  @SerializedName(SERIALIZED_NAME_NEW_APPLET_VERSION)
  private String newAppletVersion;

  public UpdateCardRequest() { 
  }

  public UpdateCardRequest cardId(String cardId) {
    
    this.cardId = cardId;
    return this;
  }

   /**
   * Identifier of card
   * @return cardId
  **/
  public String getCardId() {
    return cardId;
  }


  public void setCardId(String cardId) {
    this.cardId = cardId;
  }


  public UpdateCardRequest currentAppletVersion(String currentAppletVersion) {
    
    this.currentAppletVersion = currentAppletVersion;
    return this;
  }

   /**
   * Current applet version for update
   * @return currentAppletVersion
  **/

  public String getCurrentAppletVersion() {
    return currentAppletVersion;
  }


  public void setCurrentAppletVersion(String currentAppletVersion) {
    this.currentAppletVersion = currentAppletVersion;
  }


  public UpdateCardRequest newAppletVersion(String newAppletVersion) {
    
    this.newAppletVersion = newAppletVersion;
    return this;
  }

   /**
   * New applet version for update
   * @return newAppletVersion
  **/

  public String getNewAppletVersion() {
    return newAppletVersion;
  }


  public void setNewAppletVersion(String newAppletVersion) {
    this.newAppletVersion = newAppletVersion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCardRequest updateCardRequest = (UpdateCardRequest) o;
    return Objects.equals(this.cardId, updateCardRequest.cardId) &&
        Objects.equals(this.currentAppletVersion, updateCardRequest.currentAppletVersion) &&
        Objects.equals(this.newAppletVersion, updateCardRequest.newAppletVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardId, currentAppletVersion, newAppletVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCardRequest {\n");
    sb.append("    cardId: ").append(toIndentedString(cardId)).append("\n");
    sb.append("    currentAppletVersion: ").append(toIndentedString(currentAppletVersion)).append("\n");
    sb.append("    newAppletVersion: ").append(toIndentedString(newAppletVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

